---
output: html_document
---

<div class="my-post-main-container">

<!-- ################  CONFIGURACIONES ###################### -->

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      out.width = "60%",
                      out.height = "60%",
                      fig.align = "center")

```

Los gráficos de líneas nos permiten ver la evolución de una variable atreves del tiempo que es como generalmente se lo utilizara el grafico de líneas.

## Librerías R necesarias

```{r}
library(gcookbook)
library(reticulate)
library(ggplot2)
library(dplyr)
```

## Librerías Python necesarias

```{python}
import numpy as np
import matplotlib.pyplot as plt
```

## Grafico de líneas en R

```{r}
BOD %>%  ggplot(aes(x=Time, y=demand)) +
    geom_line()
```


## Grafico de líneas en Python

```{python, results='hide'}
plt.clf()
x=np.array(r.BOD["Time"])
y=np.array(r.BOD["demand"])
plt.plot(x,y)
plt.show()
```




</div>