---
output: html_document
---

<div class="my-post-main-container">

<!-- ################  CONFIGURACIONES ###################### -->

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      out.width = "60%",
                      out.height = "60%",
                      fig.align = "center")

```

<!-- ######################################################## -->

Los gráficos de nubes de palabras son utilizados para representan el reconteo de diferentes palabras dentro de un marco de datos.

## Librerías R necesarias

```{r}
library(wordcloud)
```

## Forma de los datos

Para generar nubes de palabras se requiere dos campos, uno que representa las palabras y otro que representa la frecuencia de dichas palabras.

```{r}
palabras <- c(letters, LETTERS, 0:9)
frecuenciaPalabras <- sample(1:100,62,TRUE)
```

## Grafico de nube de palabras con R

```{r}
wordcloud(words = palabras,
          freq = frecuenciaPalabras,
          min.freq = 3,
          max.words = Inf,
          random.order = TRUE,
          random.color = FALSE,
          rot.per = .1,
          colors = "black",
          ordered.colors = FALSE,
          use.r.layout = FALSE,
          fixed.asp = TRUE)

```

</div>