---
output: html_document
---

<div class="my-post-main-container">

<!-- ################  CONFIGURACIONES ###################### -->

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      out.width = "60%",
                      out.height = "60%",
                      fig.align = "center")

```

Los gráficos de barras son utilizado comúnmente para representar variables discretas o cualitativas, para visualizar el conteo de variables o coparación de magnitudes entre categorias.

## Librerías R necesarias

```{r}
library(gcookbook)
library(reticulate)
library(ggplot2)
library(dplyr)
```

## Librerías Python necesarias

```{python}
import numpy as np
import matplotlib.pyplot as plt
```

## Grafico de barras con R

```{r}
pg_mean %>% ggplot(aes(x=group, y=weight)) +
    geom_col()
```


## Grafico de barras con Python

```{python, results='hide'}
plt.clf()
x=np.array(r.pg_mean["group"])
y=np.array(r.pg_mean["weight"])
plt.bar(x,y)
plt.show()
```



</div>